# Generated by Django 4.2.11 on 2026-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('cabin', models.CharField(choices=[('Economy', 'Economy'), ('Premium', 'Premium'), ('Business', 'Business')], default='Economy', max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_blocked', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('flight', 'code')},
            },
        ),
    ]
