# Generated by Django 4.2.11 on 2026-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=140)),
                ('accommodation_type', models.CharField(choices=[('NONE', 'No Accommodation'), ('MEAL', 'Meal Voucher'), ('HOTEL', 'Hotel + Meal'), ('REBOOK', 'Priority Rebooking')], default='NONE', max_length=20)),
                ('message', models.CharField(max_length=220)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_alerts', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
