# Generated by Django 5.2.13 on 2026-04-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=140)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=12, unique=True)),
                ('airline', models.CharField(max_length=80)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('depart_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('seats_total', models.PositiveIntegerField(default=60)),
                ('gate', models.CharField(default='A1', max_length=10)),
                ('status', models.CharField(choices=[('CHECKIN', 'Check-in Open'), ('ON_TIME', 'On Time'), ('BOARDING', 'Boarding'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ON_TIME', max_length=20)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('checkin_open', models.BooleanField(default=True)),
                ('document_check_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['depart_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('cabin', models.CharField(choices=[('Economy', 'Economy'), ('Premium', 'Premium'), ('Business', 'Business')], default='Economy', max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_blocked', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reservations.flight')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('flight', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(blank=True, max_length=8, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('booking_mode', models.CharField(choices=[('USER', 'Passenger Booking'), ('AGENT', 'Agent Booking')], default='USER', max_length=10)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('document_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20)),
                ('checked_in', models.BooleanField(default=False)),
                ('accommodation_note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.coupon')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservations.flight')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.seat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
