# Generated by Django 4.2.11 on 2026-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=80)),
                ('manufacturer', models.CharField(default='Airbus', max_length=80)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('rows', models.PositiveIntegerField(default=10)),
                ('seats_per_row', models.PositiveIntegerField(default=6)),
            ],
            options={
                'ordering': ['tail_number'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=12, unique=True)),
                ('airline', models.CharField(max_length=80)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('depart_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gate', models.CharField(default='A1', max_length=10)),
                ('status', models.CharField(choices=[('CHECKIN', 'Check-in Open'), ('ON_TIME', 'On Time'), ('BOARDING', 'Boarding'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ON_TIME', max_length=20)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('checkin_open', models.BooleanField(default=True)),
                ('document_check_required', models.BooleanField(default=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.aircraft')),
            ],
            options={
                'ordering': ['depart_at'],
            },
        ),
    ]
